on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Verify build environment
        run: npx --no ns doctor
      - name: Create android keystore
        run: |
          mkdir certs
          echo "${{ secrets.KEYSTORE_FILE_B64 }}" | base64 -d > certs/upload.keystore
      - name: Build app, publish to github and playstore
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: android publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          PLAYSTORE_JSON_KEY_DATA: ${{ secrets.PLAYSTORE_JSON_KEY_DATA }}
